#!/bin/sh -e

# https://github.com/travis-ci/travis-ci/issues/5030
if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
  export PATH=${PATH}:/Users/travis/Library/Python/2.7/bin
fi

ulimit -s 8192

DIR=$PWD

cd `dirname $0`

./prepare

cram -v *.t

cd $DIR
