version: 0.1.{build}

os: Windows Server 2012 R2

platform: x64

branches:
  only:
    - master

skip_tags: true

install:
  - .appveyor\install.bat

build_script:
  - .appveyor\build_script.bat

test_script:
  - .appveyor\test_script.bat

